### ISSUE TITLE
Show this to ScratchAddons

### ISSUE THREAD

**Issue by Timed-kitty-cat** [CodeGuy92/ScratchWizard#1]
I would but I'm blocked.

**Comment by CodeGuy92** [comment]
~~Why are you blocked?~~
After i finish it. A PR would be nice.

**Comment by Hexigon102** [comment]
i could do it

**Comment by CodeGuy92** [comment]
> i could do it

BRUH I DIDNT FINISH IT

**Comment by Hexigon102** [comment]
> > i could do it
> 
> BRUH I DIDNT FINISH IT

ah
