### ISSUE TITLE
Add a mockup of what this theme could look like

### ISSUE THREAD

**Issue by Steve0Greatness** [CodeGuy92/ScratchWizard#2]
It would be nice to have something to work off of

**Comment by Hexigon102** [comment]
i can design some on my program( i am going to tell you when i am finnished

**Comment by CodeGuy92** [comment]
> i can design some on my program( i am going to tell you when i am finnished

[Hexigon](https://scratch.mit.edu/users/-Hexigon-/), you're 11?
Users under 13 aren't allowed on Github!

Also, no, don't make the mockup. I will do it since i am the owner

**Comment by CodeGuy92** [comment]
But i don't think we need a mockup, i already made the entire basic theme, and all i need is to fix some bugs
